using System.Collections.Frozen;

namespace TSqlFormatServices;

internal static partial class TSqlFacts
{
    public static bool IsBuiltInFunction(string functionName) => BuiltInFunctions.Contains(functionName);

    // https://learn.microsoft.com/en-us/sql/t-sql/functions/functions:
    private static readonly FrozenSet<string> BuiltInFunctions = FrozenSet.Create(StringComparer.OrdinalIgnoreCase, [
        // https://learn.microsoft.com/en-us/sql/t-sql/functions/aggregate-functions-transact-sql:
        "APPROX_COUNT_DISTINCT",
        "AVG",
        "CHECKSUM_AGG",
        "COUNT",
        "COUNT_BIG",
        "GROUPING",
        "GROUPING_ID",
        "MAX",
        "MIN",
        "STDEV",
        "STDEVP",
        "STRING_AGG",
        "SUM",
        "VAR",
        "VARP",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/ai-functions-transact-sql:
        "AI_GENERATE_EMBEDDINGS",
        "AI_GENERATE_CHUNKS",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/analytic-functions-transact-sql:
        "CUME_DIST",
        "FIRST_VALUE",
        "LAG",
        "LAST_VALUE",
        "LEAD",
        "PERCENT_RANK",
        "PERCENTILE_CONT",
        "PERCENTILE_DISC",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/bit-manipulation-functions-overview:
        "LEFT_SHIFT",
        "RIGHT_SHIFT",
        "BIT_COUNT",
        "GET_BIT",
        "SET_BIT",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/collation-functions-collationproperty-transact-sql:
        "COLLATIONPROPERTY",
        // https://learn.microsoft.com/en-us/sql/t-sql/functions/collation-functions-tertiary-weights-transact-sql:
        "TERTIARY_WEIGHTS",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/conversion-functions-transact-sql:
        "CAST",
        "CONVERT",
        "PARSE",
        "TRY_CAST",
        "TRY_CONVERT",
        "TRY_PARSE",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/cryptographic-functions-transact-sql:
        "ASYMKEY_ID",
        "ASYMKEYPROPERTY",
        "CERTPROPERTY",
        "CERT_ID",
        "CRYPT_GEN_RANDOM",
        "DECRYPTBYASYMKEY",
        "DECRYPTBYCERT",
        "DECRYPTBYKEY",
        "DECRYPTBYKEYAUTOASYMKEY",
        "DECRYPTBYKEYAUTOCERT",
        "DECRYPTBYPASSPHRASE",
        "ENCRYPTBYASYMKEY",
        "ENCRYPTBYCERT",
        "ENCRYPTBYKEY",
        "ENCRYPTBYPASSPHRASE",
        "HASHBYTES",
        "IS_OBJECTSIGNED",
        "KEY_GUID",
        "KEY_ID",
        "KEY_NAME",
        "SIGNBYASYMKEY",
        "SIGNBYCERT",
        "SYMKEYPROPERTY",
        "VERIFYSIGNEDBYCERT",
        "VERIFYSIGNEDBYASYMKEY",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/cursor-functions-transact-sql:
        "CURSOR_STATUS",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/data-type-functions-transact-sql:
        "DATALENGTH",
        "IDENT_CURRENT",
        "IDENT_INCR",
        "IDENT_SEED",
        "IDENTITY",
        "SQL_VARIANT_PROPERTY",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql:
        "CURRENT_TIMESTAMP",
        "CURRENT_TIMEZONE",
        "CURRENT_TIMEZONE_ID",
        "DATE_BUCKET",
        "DATEADD",
        "DATEDIFF",
        "DATEDIFF_BIG",
        "DATEFROMPARTS",
        "DATENAME",
        "DATEPART",
        "DATETIME2FROMPARTS",
        "DATETIMEFROMPARTS",
        "DATETIMEOFFSETFROMPARTS",
        "DATETRUNC",
        "DAY",
        "EOMONTH",
        "GETDATE",
        "GETUTCDATE",
        "ISDATE",
        "MONTH",
        "SMALLDATETIMEFROMPARTS",
        "SWITCHOFFSET",
        "SYSDATETIME",
        "SYSDATETIMEOFFSET",
        "SYSUTCDATETIME",
        "TIMEFROMPARTS",
        "TODATETIMEOFFSET",
        "YEAR",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/edit-distance-transact-sql:
        "EDIT_DISTANCE",
        // https://learn.microsoft.com/en-us/sql/t-sql/functions/edit-distance-similarity-transact-sql:
        "EDIT_DISTANCE_SIMILARITY",
        // https://learn.microsoft.com/en-us/sql/t-sql/functions/jaro-winkler-distance-transact-sql:
        "JARO_WINKLER_DISTANCE",
        // https://learn.microsoft.com/en-us/sql/t-sql/functions/jaro-winkler-similarity-transact-sql:
        "JARO_WINKLER_SIMILARITY",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/graph-functions-transact-sql:
        "EDGE_ID_FROM_PARTS",
        "GRAPH_ID_FROM_EDGE_ID",
        "GRAPH_ID_FROM_NODE_ID",
        "NODE_ID_FROM_PARTS",
        "OBJECT_ID_FROM_EDGE_ID",
        "OBJECT_ID_FROM_NODE_ID",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/json-functions-transact-sql:
        "ISJSON",
        "JSON_ARRAY",
        "JSON_CONTAINS",
        "JSON_MODIFY",
        "JSON_OBJECT",
        "JSON_PATH_EXISTS",
        "JSON_QUERY",
        "JSON_VALUE",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/regular-expressions-functions-transact-sql:
        "REGEXP_LIKE",
        "REGEXP_REPLACE",
        "REGEXP_SUBSTR",
        "REGEXP_INSTR",
        "REGEXP_COUNT",
        "REGEXP_MATCHES",
        "REGEXP_SPLIT_TO_TABLE",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/mathematical-functions-transact-sql:
        "ABS",
        "ACOS",
        "ASIN",
        "ATAN",
        "ATN2",
        "CEILING",
        "COS",
        "COT",
        "DEGREES",
        "EXP",
        "FLOOR",
        "LOG",
        "LOG10",
        "PI",
        "POWER",
        "RADIANS",
        "RAND",
        "ROUND",
        "SIGN",
        "SIN",
        "SQRT",
        "SQUARE",
        "TAN",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/logical-functions-choose-transact-sql:
        "CHOOSE",
        // https://learn.microsoft.com/en-us/sql/t-sql/functions/logical-functions-greatest-transact-sql:
        "GREATEST",
        // https://learn.microsoft.com/en-us/sql/t-sql/functions/logical-functions-iif-transact-sql:
        "IIF",
        // https://learn.microsoft.com/en-us/sql/t-sql/functions/logical-functions-least-transact-sql:
        "LEAST",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/metadata-functions-transact-sql:
        "APP_NAME",
        "APPLOCK_MODE",
        "APPLOCK_TEST",
        "ASSEMBLYPROPERTY",
        "COL_LENGTH",
        "COL_NAME",
        "COLUMNPROPERTY",
        "DATABASEPROPERTYEX",
        "DB_ID",
        "DB_NAME",
        "FILE_ID",
        "FILE_IDEX",
        "FILE_NAME",
        "FILEGROUP_ID",
        "FILEGROUP_NAME",
        "FILEGROUPPROPERTY",
        "FILEPROPERTY",
        "FILEPROPERTYEX",
        "FULLTEXTCATALOGPROPERTY",
        "FULLTEXTSERVICEPROPERTY",
        "INDEX_COL",
        "INDEXKEY_PROPERTY",
        "INDEXPROPERTY",
        "NEXT VALUE FOR",
        "OBJECT_DEFINITION",
        "OBJECT_ID",
        "OBJECT_NAME",
        "OBJECT_SCHEMA_NAME",
        "OBJECTPROPERTY",
        "OBJECTPROPERTYEX",
        "ORIGINAL_DB_NAME",
        "PARSENAME",
        "SCHEMA_ID",
        "SCHEMA_NAME",
        "SCOPE_IDENTITY",
        "SERVERPROPERTY",
        "STATS_DATE",
        "TYPE_ID",
        "TYPE_NAME",
        "TYPEPROPERTY",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/ranking-functions-transact-sql:
        "DENSE_RANK",
        "NTILE",
        "RANK",
        "ROW_NUMBER",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/replication-functions-publishingservername:
        "PUBLISHINGSERVERNAME",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/security-functions-transact-sql:
        "CERTENCODED",
        "CERTPRIVATEKEY",
        "CURRENT_USER",
        "DATABASE_PRINCIPAL_ID",
        "HAS_DBACCESS",
        "HAS_PERMS_BY_NAME",
        "IS_MEMBER",
        "IS_ROLEMEMBER",
        "IS_SRVROLEMEMBER",
        "LOGINPROPERTY",
        "ORIGINAL_LOGIN",
        "PERMISSIONS",
        "PWDENCRYPT",
        "PWDCOMPARE",
        "SESSION_USER",
        "SESSIONPROPERTY",
        "SUSER_ID",
        "SUSER_NAME",
        "SUSER_SID",
        "SUSER_SNAME",
        "SYSTEM_USER",
        "USER",
        "USER_ID",
        "USER_NAME",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/string-functions-transact-sql:
        "ASCII",
        "CHAR",
        "CHARINDEX",
        "CONCAT",
        "CONCAT_WS",
        "DIFFERENCE",
        "FORMAT",
        "LEFT",
        "LEN",
        "LOWER",
        "LTRIM",
        "NCHAR",
        "PATINDEX",
        "QUOTENAME",
        "REPLACE",
        "REPLICATE",
        "REVERSE",
        "RIGHT",
        "RTRIM",
        "SOUNDEX",
        "SPACE",
        "STR",
        "STRING_AGG",
        "STRING_ESCAPE",
        "STUFF",
        "SUBSTRING",
        "TRANSLATE",
        "TRIM",
        "UNICODE",
        "UPPER",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/system-functions-transact-sql:
        "BINARY_CHECKSUM",
        "CHECKSUM",
        "COMPRESS",
        "CONNECTIONPROPERTY",
        "CONTEXT_INFO",
        "CURRENT_REQUEST_ID",
        "CURRENT_TRANSACTION_ID",
        "DECOMPRESS",
        "ERROR_LINE",
        "ERROR_MESSAGE",
        "ERROR_NUMBER",
        "ERROR_PROCEDURE",
        "ERROR_SEVERITY",
        "ERROR_STATE",
        "FORMATMESSAGE",
        "GET_FILESTREAM_TRANSACTION_CONTEXT",
        "GETANSINULL",
        "HOST_ID",
        "HOST_NAME",
        "ISNULL",
        "ISNUMERIC",
        "MIN_ACTIVE_ROWVERSION",
        "NEWID",
        "NEWSEQUENTIALID",
        "ROWCOUNT_BIG",
        "SESSION_CONTEXT",
        "XACT_STATE",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/text-and-image-functions-textptr-transact-sql:
        "TEXTPTR",
        // https://learn.microsoft.com/en-us/sql/t-sql/functions/text-and-image-functions-textvalid-transact-sql:
        "TEXTVALID",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/trigger-functions-transact-sql:
        "COLUMNS_UPDATED",
        "EVENTDATA",
        "TRIGGER_NESTLEVEL",
        "UPDATE",

        // https://learn.microsoft.com/en-us/sql/t-sql/functions/vector-functions-transact-sql:
        "VECTOR_DISTANCE",
        "VECTORPROPERTY",
        "VECTOR_SEARCH",
    ]);
}
